<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerK3TclaF\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerK3TclaF/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerK3TclaF.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerK3TclaF\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerK3TclaF\App_KernelDevDebugContainer([
    'container.build_hash' => 'K3TclaF',
    'container.build_id' => '9d4dde5d',
    'container.build_time' => 1613468081,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerK3TclaF');
